### ISSUE TITLE
Mention suggestions not cleard after clear text

### ISSUE THREAD

**Issue by Gursewak-Uppal** [fayeed/flutter_mentions#4]
I tried this plugin but when i cleared all text form Text Input (FlutterMentions) Mention suggestions list is still there. Also when i selected item it gives me error. I think it's work only with trigger (@, #).

Error logs

   ```
 I/flutter (31840): The following RangeError was thrown while handling a gesture:
I/flutter (31840): RangeError (end): Invalid value: Only valid value is 0: 2
I/flutter (31840): 
I/flutter (31840): When the exception was thrown, this was the stack:
I/flutter (31840): #0      RangeError.checkValidRange (dart:core/errors.dart:357:9)
I/flutter (31840): #1      _StringBase.replaceRange (dart:core-patch/string_patch.dart:601:33)
I/flutter (31840): #2      FlutterMentionsState.build.<anonymous closure> (package:flutter_mentions/src/mention_view.dart:333:59)
I/flutter (31840): #3      OptionList.build.<anonymous closure>.<anonymous closure> (package:flutter_mentions/src/option_list.dart:37:20)
I/flutter (31840): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
I/flutter (31840): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
I/flutter (31840): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
I/flutter (31840): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
I/flutter (31840): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
I/flutter (31840): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
I/flutter (31840): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
I/flutter (31840): #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
I/flutter (31840): #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
I/flutter (31840): #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
I/flutter (31840): #17     _invoke1 (dart:ui/hooks.dart:267:10)
I/flutter (31840): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
I/flutter (31840): (elided 3 frames from dart:async)
I/flutter (31840): 
I/flutter (31840): Handler: "onTap"
I/flutter (31840): Recognizer:
I/flutter (31840):   TapGestureRecognizer#9b96e
```

**Comment by fayeed** [comment]
@Gursewak-Uppal Thanks for reporting the issue, I will take a look and let you know, If I can reproduce this.

**Comment by fayeed** [comment]
@Gursewak-Uppal I was not able to reproduce this issue if you can explain in more detail what you did that would be great help.
